services:
    weather-dashboard:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4200:3000
        networks:
            - network
networks:
    network:
        driver: bridge
